version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "expense-processor-stack"
s3_prefix = "expense-processor-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
image_repositories = []
