/*
 * This source file was generated by the Gradle 'init' task
 */
package org.finance.expenseprocessor;

import org.junit.jupiter.api.Test;

class ExpenseProcessorTest {
    @Test void appHasAGreeting() {
        ExpenseProcessor classUnderTest = new ExpenseProcessor();
    }
}
